### ISSUE TITLE
Update to v11

### ISSUE THREAD

**Issue by r-valyar** [Cardagon/popout-resizer#15]
The module requires update to v11 in order to continue function. is there plan to do this update or this is the module abandoned now?

**Comment by nschoenwald** [comment]
Would love to see an update to this module!

**Comment by Gerark** [comment]
Any update? :)

**Comment by maxerature** [comment]
Paging mister Cardagon

**Comment by Cardagon** [comment]
Sorry for the delay everyone, life and my real job have kept me very busy! I've updated the module to work with V11 :) Enjoy!
https://github.com/Cardagon/popout-resizer/releases/tag/v1.5.1

Package should be updated on foundryvtt as well.
