### ISSUE TITLE
REQUEST: Chat room popout?

### ISSUE THREAD

**Issue by GambetTV** [Cardagon/popout-resizer#6]
Any way we could make it possible to pop the chat room out into its own window?

**Comment by Cardagon** [comment]
Hey! Sorry for such a late reply.
You should be able to right click the chat button to pop it out into its own window, and then resize should work however you need it to. If you are interested in popping it out into its own browser window or tab, look into the module "Popout!", it does what you are requesting and plays nicely with my module. :)
