### ISSUE TITLE
No translation available

### ISSUE THREAD

**Issue by BlueSkyBlackBird** [Cardagon/popout-resizer#7]
I would like to add a German translation to the system but I just saw you are not using any localization. Could please integrate the i18n translation so that adding a translation file is possible? 
Thank you

**Comment by Cardagon** [comment]
Sure! I'll take a look at that this week and reply back when it's done!

**Comment by BlueSkyBlackBird** [comment]
Thank you, it should not be much work on your end.

**Comment by Cardagon** [comment]
Done! I've added the localization for settings and error message.
Let me know if you spot anything that might still be missing from the localization and I can add that too, otherwise its all yours!

**Comment by Cardagon** [comment]
Closing this now as the change has been merged and released to the latest version (v1.4.1). Thanks!
