### ISSUE TITLE
Support with foundry v9.X

### ISSUE THREAD

**Issue by CaosFR** [Cardagon/popout-resizer#9]
Hi,

Simple question that many would like to know. Is your module compatible with v9.X? Have any tests been carried out?

I'm refer to : https://docs.google.com/spreadsheets/d/1ppPR348igxL75M_G7dWl3otzXYpPwrnj7NVSDP8GmVw/edit#gid=0

Thanks
Bests regards

**Comment by jessesmall** [comment]
Thanks for the heads up! I'll be sure to test this in the next couple days and update! Based on the changes I wouldn't expect any issues but I'll make sure to test.

**Comment by CaosFR** [comment]
Thanks for your quick reply :)

**Comment by jessesmall** [comment]
I have tested on V9 and can confirm that everything is working as expected. I have updated the add-on to show support for V9. Thanks.

**Comment by CaosFR** [comment]
Great :), thanks for your tests.
